In [1]:
import pandas as pd
import openpyxl

arquivo = "Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

df = pd.read_excel(arquivo)

df

,"Tabela 10063 - Pessoas com nível superior completo, por áreas gerais, específicas e detalhadas de formação do curso graduação concluído, segundo os grupos de idade, o sexo e a cor ou raça",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,"Brasil, Grande Região e Unidade da Federação",Total,NaN,NaN,"Ciência, Tecnologia, Engenharias e Matemática",NaN,NaN,"Educação, Serviços pessoais, Saúde e Bem-estar",NaN,NaN
1,NaN,Total,Homens,Mulheres,Total,Homens,Mulheres,Total,Homens,Mulheres
2,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
3,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
4,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
5,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
6,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
7,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
8,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
9,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
10,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
11,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
12,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
13,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
14,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
15,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
16,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
17,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
18,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
19,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
20,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
21,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
22,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
23,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
24,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
25,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
26,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
27,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
28,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
29,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
30,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
31,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
32,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
33,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
34,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538
35,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import pandas as pd

dados = {
    "Região": [
        "Norte",
        "Nordeste",
        "Sudeste",
        "Sul",
        "Centro-Oeste"
    ],
    
    "Superior_Homens": [
        590558,
        1744994,
        5391638,
        1768855,
        982489
    ],
    
    "Superior_Mulheres": [
        934609,
        3003939,
        7437191,
        2570005,
        14300013
    ],
    
    "CTEM_Homens" : [
        590558,
        1744994,
        5391638,
        1768855,
        982489
    ],
    
    "CTEM_Mulheres": [
        76601,
        231395,
        739247,
        235543,
        115834
    ],
    
    "Educacao_Servicos_Saude_Homens": [
        141169,
        363905,
        768288,
        248574,
        156048
    ],
    
    "Educacao_Servicos_Saude_Mulheres": [
        458616,
        1458181,
        2884108,
        1007718,
        593101
        
    ]
}

df = pd.DataFrame(dados)

df

,Região,Superior_Homens,Superior_Mulheres,CTEM_Homens,CTEM_Mulheres,Educacao_Servicos_Saude_Homens,Educacao_Servicos_Saude_Mulheres
0,Norte,590558,934609,590558,76601,141169,458616
1,Nordeste,1744994,3003939,1744994,231395,363905,1458181
2,Sudeste,5391638,7437191,5391638,739247,768288,2884108
3,Sul,1768855,2570005,1768855,235543,248574,1007718
4,Centro-Oeste,982489,14300013,982489,115834,156048,593101

In [3]:
tabela_superior = df.loc[:,[
    "Região",
    "Superior_Homens",
    "Superior_Mulheres"
]]

tabela_superior

         Região  Superior_Homens  Superior_Mulheres
0         Norte           590558             934609
1      Nordeste          1744994            3003939
2       Sudeste          5391638            7437191
3           Sul          1768855            2570005
4  Centro-Oeste           982489           14300013

In [4]:
tabela_superior.describe()

       Superior_Homens  Superior_Mulheres
count     5.000000e+00       5.000000e+00
mean      2.095707e+06       5.649151e+06
std       1.910348e+06       5.402307e+06
min       5.905580e+05       9.346090e+05
25%       9.824890e+05       2.570005e+06
50%       1.744994e+06       3.003939e+06
75%       1.768855e+06       7.437191e+06
max       5.391638e+06       1.430001e+07

In [7]:
tabela_ctem = df.loc[:,[
    "Região",
    "CTEM_Homens",
    "CTEM_Mulheres"
]]

tabela_ctem

         Região  CTEM_Homens  CTEM_Mulheres
0         Norte       590558          76601
1      Nordeste      1744994         231395
2       Sudeste      5391638         739247
3           Sul      1768855         235543
4  Centro-Oeste       982489         115834

In [8]:
tabela_ctem.describe()

        CTEM_Homens  CTEM_Mulheres
count  5.000000e+00       5.000000
mean   2.095707e+06  279724.000000
std    1.910348e+06  266255.481521
min    5.905580e+05   76601.000000
25%    9.824890e+05  115834.000000
50%    1.744994e+06  231395.000000
75%    1.768855e+06  235543.000000
max    5.391638e+06  739247.000000

In [11]:
tabela_educacao = df.loc[:,[
    "Região",
    "Educacao_Servicos_Saude_Homens",
    "Educacao_Servicos_Saude_Mulheres"
]]

tabela_educacao

,Região,Educacao_Servicos_Saude_Homens,Educacao_Servicos_Saude_Mulheres
0,Norte,141169,458616
1,Nordeste,363905,1458181
2,Sudeste,768288,2884108
3,Sul,248574,1007718
4,Centro-Oeste,156048,593101

In [12]:
tabela_educacao.describe()

       Educacao_Servicos_Saude_Homens  Educacao_Servicos_Saude_Mulheres
count                        5.000000                      5.000000e+00
mean                    335596.800000                      1.280345e+06
std                     257699.406993                      9.779506e+05
min                     141169.000000                      4.586160e+05
25%                     156048.000000                      5.931010e+05
50%                     248574.000000                      1.007718e+06
75%                     363905.000000                      1.458181e+06
max                     768288.000000                      2.884108e+06

In [13]:
print("ESTATÍSTICAS --CURSO SUPERIOR")
display(tabela_superior.describe())

print("ESTATÍSTICAS --CIÊNCIA, TECNOLOGIA, ENGENHARIAS E MATEMÁTICA")
display(tabela_ctem.describe())

print("ESTATÍSTICAS --EDUCAÇÃO, SERVIÇOS PESSOAIS, SAUDE E BEM-ESTAR")
display(tabela_educacao.describe())

ESTATÍSTICAS --CURSO SUPERIOR

       Superior_Homens  Superior_Mulheres
count     5.000000e+00       5.000000e+00
mean      2.095707e+06       5.649151e+06
std       1.910348e+06       5.402307e+06
min       5.905580e+05       9.346090e+05
25%       9.824890e+05       2.570005e+06
50%       1.744994e+06       3.003939e+06
75%       1.768855e+06       7.437191e+06
max       5.391638e+06       1.430001e+07

ESTATÍSTICAS --CIÊNCIA, TECNOLOGIA, ENGENHARIAS E MATEMÁTICA

        CTEM_Homens  CTEM_Mulheres
count  5.000000e+00       5.000000
mean   2.095707e+06  279724.000000
std    1.910348e+06  266255.481521
min    5.905580e+05   76601.000000
25%    9.824890e+05  115834.000000
50%    1.744994e+06  231395.000000
75%    1.768855e+06  235543.000000
max    5.391638e+06  739247.000000

ESTATÍSTICAS --EDUCAÇÃO, SERVIÇOS PESSOAIS, SAUDE E BEM-ESTAR

       Educacao_Servicos_Saude_Homens  Educacao_Servicos_Saude_Mulheres
count                        5.000000                      5.000000e+00
mean                    335596.800000                      1.280345e+06
std                     257699.406993                      9.779506e+05
min                     141169.000000                      4.586160e+05
25%                     156048.000000                      5.931010e+05
50%                     248574.000000                      1.007718e+06
75%                     363905.000000                      1.458181e+06
max                     768288.000000                      2.884108e+06